// User-supplied visual references. Authorship has not been established.
const shared={source:'master',group:'你选的三种',font:'auto',credit:'用户提供参考 · 作者未核实',fontNote:'按截图测量布局；使用本机宋体、楷体和 Helvetica 近似原字体。背景为去字重建示例，可上传自己的照片。'};
export const masterPresets=[
 {...shared,id:'tea-reference',name:'拾間 · 上图下纸',composition:'master:tea',ratio:'856:1138',bookWidth:856,bookHeight:1138,colors:['#f5f0e0','#080a07','#f5f2e9'],referenceImage:'/public/selected-tea.png',backgroundImage:'/public/background-tea.png',copy:{title:'拾\n間',subtitle:'Natural Season\nAnd\nOriental',kicker:'东 方 新 式 茶 馆',brand:'SHIJIAN',eyebrow:'',vertical:'东方之野',left:'新\n式',right:'茶\n馆',metaLeft:'',metaRight:'',body:'Crossing the Four Seasons and Eight Festivals,\nExperience the Wilderness of the East',fineprint:''}},
 {...shared,id:'forest-reference',name:'QINSAYO · 满版树林',composition:'master:forest',ratio:'766:1092',bookWidth:766,bookHeight:1092,colors:['#222a17','#ffffff','#ffffff'],referenceImage:'/public/selected-forest.png',backgroundImage:'/public/background-forest.png',copy:{title:'城市\n高楼中的一座\n青山',subtitle:"GREEN HILL IN THE CITY’S\nTALL BUILDINGS",kicker:'FLOWERSCENTED\nPURE TEA',brand:'QINSAYO',eyebrow:'城市清野茶时空',vertical:'',left:'',right:'',metaLeft:'',metaRight:'',body:'',fineprint:''}},
 {...shared,id:'fields-reference',name:'GREEN FIELDS · 倒置标题',composition:'master:fields',ratio:'788:1102',bookWidth:788,bookHeight:1102,colors:['#50683f','#0e1c09','#a7d77a'],referenceImage:'/public/selected-fields.png',backgroundImage:'/public/background-fields.png',copy:{title:'BEYOND\nGREEN FIELDS',subtitle:'',kicker:'BALI / GLOBAL',brand:'',eyebrow:'',vertical:'',left:'JUNE. 10 / 23\nMMXXII',right:'11 AM — 04 PM\nGMT +3',metaLeft:'GLOBUSVERSE\nPRESENTS',metaRight:'BALI\nFLIGHT D47B',body:'WWW.GLOBUSVERSE.COM\nWITH EVERYONE',fineprint:'7°45′ S 115° — 13° E\nGLOBAL COORDINATES'}}
];
export const masterFields=['title','subtitle','kicker','brand','eyebrow','vertical','left','right','metaLeft','metaRight','body','fineprint'];
export function applyMaster(previous,p,index){return {...previous,layout:index,combination:null,ratio:p.ratio,bg:p.colors[0],fg:p.colors[1],accent:p.colors[2],font:'auto',fontSize:110,layers:{...previous.layers,background:true,image:true,text:true,ornament:true},serial:(previous.serial||0)+1};}
